spring.application.name=Bank_Account_Management
server.port=7031
spring.datasource.url=jdbc:mysql://localhost:3306/Bank?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true